package de.upteams.tasktracker.project.utils;

import de.upteams.tasktracker.project.dto.request.ProjectCreateDto;
import de.upteams.tasktracker.project.dto.response.ProjectResponseDto;
import de.upteams.tasktracker.project.entity.Project;
import de.upteams.tasktracker.task.utils.TaskMappingService;
import de.upteams.tasktracker.user.util.AppUserMapper;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;
import org.mapstruct.Named;

import java.util.UUID;

/**
 * Interface for Project Mapping Service.
 * Implementation of that interface is generated by MapStruct framework.
 */
@Mapper(
        componentModel = MappingConstants.ComponentModel.SPRING,
        uses = {AppUserMapper.class, TaskMappingService.class}
)
public interface ProjectMapper {

    @Mapping(source = "owner", target = "owner")
    ProjectResponseDto mapEntityToDto(Project entity);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "tasks", ignore = true)
    @Mapping(target = "projectTeam", ignore = true)
    Project mapDtoToEntity(ProjectCreateDto dto);

    @Named("uuidToString")
    default String mapId(UUID id) {
        return id == null ? null : id.toString();
    }
}